# docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    container_name: flixpatrol-api
    ports:
      - "127.0.0.1:8001:8000"
    env_file:
      - .env
    environment:
      - REDIS_TYPE=local
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6380
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
